const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Behaviors.Flash,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{arkaplan: 0},
	{ipucuText: 0},
	{clicked: 0},
	{ipucuBtn: 0},
	{iskelet: 0},
	{val: 0},
	{isActive: 0},
	{isClicked: 0},
	{topLeft: 0},
	{bottomRight: 0},
	{bottomLeft: 0},
	{Fade: 0},
	{okText: 0},
	{Flash: 0},
	{ok: 0},
	{endPosY: 0},
	{firstPosY: 0},
	{numerikKeyboardBg: 0},
	{value: 0},
	{id: 0},
	{Enter: 0},
	{X: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{delete: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{topRight: 0},
	{Sine: 0},
	{imlec: 0},
	{Mouse: 0},
	{inputText: 0},
	{randomArray: 0},
	{Audio: 0},
	{AJAX: 0},
	{veriJSON: 0},
	{bottomRightBg: 0},
	{tuslar: 0},
	{inputs: 0},
	{ipucuKontrol: 0},
	{activeInputIndex: 0},
	{answerHealth: 0},
	{LeftX: 0},
	{rightX: 0},
	{LeftOkTextX: 0},
	{rightOkTextX: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	ipucuText: class extends self.ISpriteInstance {},
	ipucuBtn: class extends self.ISpriteInstance {},
	iskelet: class extends self.ISpriteInstance {},
	topLeft: class extends self.ISpriteInstance {},
	bottomRight: class extends self.ISpriteInstance {},
	bottomLeft: class extends self.ISpriteInstance {},
	okText: class extends self.ISpriteInstance {},
	ok: class extends self.ISpriteInstance {},
	numerikKeyboardBg: class extends self.ISpriteInstance {},
	Enter: class extends self.ISpriteInstance {},
	X: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	delete: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	topRight: class extends self.ISpriteInstance {},
	imlec: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	inputText: class extends self.ITextInstance {},
	randomArray: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	veriJSON: class extends self.IJSONInstance {},
	bottomRightBg: class extends self.ISpriteInstance {},
	tuslar: class extends self.ISpriteInstance {},
	inputs: class extends self.ISpriteInstance {}
}